doc/urls.py
from django.urls import path

from . import views

app_name = 'doc'

urlpatterns = [
    path('create', views.DocCreateView.as_view(), name='create'),
    path('<int:pk>/update', views.DocUpdateView.as_view(), name='update'),
    path('<int:pk>/download', views.DocDownloadView.as_view(), name='download'),
    path('<int:pk>/editor', views.DocEditorView.as_view(), name='editor'),
    path('', views.DocListView.as_view(), name='list'),
    path('navigator', views.DocNavigatorList.as_view(), name='navigator_list'),
    path('navigator/<str:pk>/editor', views.DocNavigatorEditorView.as_view(), name='navigator_editor'),
    path('filter', views.FilteredDocListView.as_view(), name='filter')
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
]

main/models.py
# Create your models here.

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView


class Home(LoginRequiredMixin, TemplateView):

    template_name = 'main/home.html'


class Editor(LoginRequiredMixin, TemplateView):
    template_name = 'main/editor.html'

templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <a href="{% url 'doc:list' %}" class="btn btn-primary">Список документов</a>
        <a href="{% url 'doc:navigator_list' %}" class="btn btn-primary">Список документов SPNavigator</a>
    </div>
{% endblock %}