doc/api/urls.py
from django.urls import path

from . import views

app_name = 'doc'

urlpatterns = [
    path('from/markdown/to/html', views.FromMarkdownToHtml.as_view(), name='from_markdown_to_html'),
    path('markdown/<int:pk>/save', views.MarkdownSave.as_view(), name='markdown_save'),
    path('markdown/<int:pk>/load', views.MarkdownLoad.as_view(), name='markdown_load'),
    path('markdown/navigator/<uuid:pk>/save', views.MarkdownNavigatorSave.as_view(), name='markdown_navigator_save'),
    path('markdown/navigator/<uuid:pk>/load', views.MarkdownNavigatorLoad.as_view(), name='markdown_navigator_load'),
    # path('document/<uuid:uid>', views.DocView.as_view(), name='doc_view'),
    # path('document/<int:pk>', views.DocView.as_view(), name='doc_view'),
    # path('document/<int:pk>/log/viewing', views.DocLogViewingView.as_view(), name='doc_log_viewing_view'),
    # path('document/<uuid:uid>/log/viewing', views.DocLogViewingView.as_view(), name='doc_log_viewing_view'),
]

doc/urls.py
from django.urls import path

from . import views

app_name = 'doc'

urlpatterns = [
    path('create', views.DocCreateView.as_view(), name='create'),
    path('<int:pk>/update', views.DocUpdateView.as_view(), name='update'),
    path('<int:pk>/download', views.DocDownloadView.as_view(), name='download'),
    path('<int:pk>/editor', views.DocEditorView.as_view(), name='editor'),
    path('', views.DocListView.as_view(), name='list'),
    path('navigator', views.DocNavigatorList.as_view(), name='navigator_list'),
    path('navigator/<str:pk>/editor', views.DocNavigatorEditorView.as_view(), name='navigator_editor'),
    path('filter', views.FilteredDocListView.as_view(), name='filter')
]

doc/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models import ForeignKey, CharField, FileField, Model, PROTECT, SmallIntegerField
from django_mysql.models import JSONField
from model_utils.models import TimeStampedModel
from simple_history.models import HistoricalRecords

from core.models import CodeNameModel, NameModel


class Category(CodeNameModel):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Project(CodeNameModel):
    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'


class Doc(TimeStampedModel, NameModel):
    STATUS_NOTHING = 0
    STATUS_UPLOADED = 1
    STATUS_WORK = 2
    STATUS_PREPARED = 3
    STATUS_ERRORS = 4
    STATUS_COMPLETE = 5
    STATUS_CHOICES = (
        (STATUS_NOTHING, 'ничего'),
        (STATUS_UPLOADED, 'загружено'),
        (STATUS_WORK, 'в работе'),
        (STATUS_PREPARED, 'подготовлено'),
        (STATUS_ERRORS, 'ошибки'),
        (STATUS_COMPLETE, 'выполнено'),
    )
    project = ForeignKey(Project, related_name='docs', verbose_name='Проекты', on_delete=PROTECT, default=1)
    owner = ForeignKey(get_user_model(), related_name='docs', verbose_name='Владелец', on_delete=PROTECT)
    name = CharField('Название', max_length=256)
    category = ForeignKey(Category, related_name='docs', verbose_name='Категория', on_delete=PROTECT)
    file_archive = FileField('Архивный файл', upload_to='uploads/%Y%m%d/', null=True)
    status = SmallIntegerField('Статус', default=STATUS_NOTHING, choices=STATUS_CHOICES)
    history = HistoricalRecords()
    extra_data = JSONField(default=dict)

    def get_markdown_path(self):
        return settings.STORAGE_ROOT / 'markdown' / str(self.id)

    def get_markdown_filepath(self):
        return self.get_markdown_path() / 'index.md'

    def get_bibliography_filepath(self):
        return self.get_markdown_path() / 'bibliography.md'

    def get_media_path(self):
        return settings.MEDIA_ROOT / 'markdown' / str(self.id)

    def get_media_url(self):
        return '{}markdown/{}/'.format(settings.MEDIA_URL, str(self.id))

    def get_storage_path(self):
        return settings.STORAGE_ROOT / 'indesign' / str(self.id)

    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'

doc/forms.py
from django.forms import ModelForm

import django_filters

from . import models



class DocForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = models.Doc
        fields = ('name', 'project', 'file_archive', 'category',)

class DocFilterForm(django_filters.FilterSet):
    class Meta:
        model = models.Doc
        fields = ['status', 'project']

doc/api/views.py
import json

import urllib3
from django.conf import settings
from rest_framework import status
from rest_framework.generics import UpdateAPIView, RetrieveAPIView
from rest_framework.response import Response
from rest_framework.views import APIView

from converter.utils import to_html
from .. import models


class FromMarkdownToHtml(APIView):
    def post(self, request, *args, **kwargs):
        md_text = request.POST.get('markdown_content', '')
        uid = request.POST.get('uid')
        html = to_html(md_text, uid)
        return Response(html, status=status.HTTP_200_OK, headers={})


class MarkdownDictObjectMixin(object):
    def get_object_dict(self):
        self.object = self.get_object()
        data = dict(
            markdown_content=self.object.get_markdown_filepath().read_text(encoding='utf-8'),
            markdown_prefix=self.object.get_media_url(),
            name=self.object.name,
            status=self.object.status,
        )
        return data


class MarkdownLoad(MarkdownDictObjectMixin, RetrieveAPIView):
    queryset = models.Doc.objects

    def retrieve(self, request, *args, **kwargs):
        data = self.get_object_dict()
        return Response(data, status=status.HTTP_200_OK)


class MarkdownSave(MarkdownDictObjectMixin, UpdateAPIView):
    queryset = models.Doc.objects

    def update(self, request, *args, **kwargs):
        doc = self.get_object()
        if 'markdown_content' in request.data:
            markdown_content = request.data.get('markdown_content')
            if not markdown_content:
                return Response(status=status.HTTP_400_BAD_REQUEST)
            doc.get_markdown_filepath().write_text(markdown_content, encoding='utf-8')
            doc.status = models.Doc.STATUS_WORK
            doc.save()
        elif 'status' in request.data:
            doc.status = request.data['status']
            doc.save()
        data = self.get_object_dict()
        return Response(data, status=status.HTTP_200_OK)


class MarkdownNavigatorLoad(RetrieveAPIView):
    def retrieve(self, request, *args, **kwargs):
        pool = urllib3.PoolManager()
        url = settings.SPNAVIGATOR_API.format(url='storage/document/{uid}/get/for/editor'.format(uid=self.kwargs['pk']))
        res = pool.request('GET', url, headers={'Authorization': 'Token39 {}'.format(self.request.user.profile.token39)})
        data = json.loads(res.data.decode('utf-8'))
        markdown_content = data['data']
        markdown_prefix = settings.SPNAVIGATOR_BASE.format(url=data['src_prefix'])
        return Response({'markdown_content': markdown_content, 'markdown_prefix': markdown_prefix}, status=status.HTTP_200_OK)


class MarkdownNavigatorSave(UpdateAPIView):
    queryset = models.Doc.objects

    def update(self, request, *args, **kwargs):
        doc = self.get_object()
        markdown_content = request.data.get('markdown_content')
        if not markdown_content:
            return Response(status=status.HTTP_400_BAD_REQUEST)
        doc.get_markdown_filepath().write_text(markdown_content, encoding='utf-8')
        return Response({'markdown_content': markdown_content}, status=status.HTTP_200_OK)

doc/views.py
import json
import re
import shutil
from io import BytesIO
from operator import itemgetter
from zipfile import ZipFile

import urllib3
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import ChoiceField
from django.http import HttpResponse
from django.urls import reverse_lazy, reverse
from django.utils import dateparse
from django.views.generic import CreateView, UpdateView, ListView, DetailView, TemplateView
from rest_framework import status

from converter.utils import convert
from core.utils import rfc5987_content_disposition
from . import forms
from . import models


class DocListView(LoginRequiredMixin, ListView):
    template_name = 'doc/list.html'

    def get_queryset(self):
        queryset = models.Doc.objects
        if not self.request.user.is_superuser:
            queryset = queryset.filter(owner=self.request.user)
        return queryset.order_by('-modified')

    def get_context_data(self, **kwargs):
        context = super(DocListView, self).get_context_data(**kwargs)
        context['filter'] = forms.DocFilterForm(self.request.GET)
        return context	


class FilteredDocListView(DocListView):

    def get_queryset(self):
        queryset = super().get_queryset()
        filtred = forms.DocFilterForm(self.request.GET, queryset=queryset)
        return filtred.qs


class DocExtractMixin(object):
    # TODO разобраться с разархивацией и переименованием файлов на латиницу
    def extract_file(self, doc):
        path = doc.get_storage_path()
        with ZipFile(doc.file_archive.file, 'r') as z:
            z.extractall(path)
            for name in z.namelist():
                unicode_name = name.encode('cp437').decode('cp866')
                fullpath = path / unicode_name
                if z.getinfo(name).is_dir():
                    fullpath.mkdir(parents=True, exist_ok=True)
                else:
                    with z.open(name) as f:
                        content = f.read()
                        with open(fullpath, 'wb') as f:
                            f.write(content)
        in_file = list(path.glob('*.html'))[0]
        media_path = doc.get_media_path()
        media_path.mkdir(parents=True, exist_ok=True)
        convert_result = convert(in_file, str(media_path))
        doc.extra_data['convert_result'] = convert_result
        markdown_path = doc.get_markdown_path()
        markdown_path.mkdir(parents=True, exist_ok=True)
        shutil.copy(media_path / 'index.md', markdown_path / 'index.md')
        # (media_path / 'index.md').unlink()


class DocCreateView(LoginRequiredMixin, DocExtractMixin, CreateView):
    queryset = models.Doc.objects
    form_class = forms.DocForm
    template_name = 'doc/create.html'
    success_url = reverse_lazy('doc:list')

    # def get_initial(self):
    #     return {'owner': self.request.user}

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.status = models.Doc.STATUS_UPLOADED
        ret = super().form_valid(form)
        self.extract_file(form.instance)
        form.instance.save()
        return ret


class DocUpdateView(LoginRequiredMixin, DocExtractMixin, UpdateView):
    queryset = models.Doc.objects
    form_class = forms.DocForm
    template_name = 'doc/update.html'

    # success_url = reverse_lazy('doc:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'convert_result' in self.object.extra_data and \
                'unknown_colors' in self.object.extra_data['convert_result'] and \
                self.object.extra_data['convert_result']['unknown_colors']:
            context['unknown_colors'] = [(x, ChoiceField(choices=('---', 'Полужирный', 'Крик', 'Врезка')))
                                         for x in self.object.extra_data['convert_result']['unknown_colors']]
        return context

    def form_valid(self, form):
        form.instance.status = models.Doc.STATUS_UPLOADED if form.instance.file_archive else models.Doc.STATUS_NOTHING
        ret = super().form_valid(form)
        self.extract_file(form.instance)
        form.instance.save()
        return ret

    def get_success_url(self):
        if 'convert_result' in self.object.extra_data and \
                'unknown_colors' in self.object.extra_data['convert_result'] and \
                self.object.extra_data['convert_result']['unknown_colors']:
            return reverse('doc:update', args=[self.object.id, ])
        else:
            return reverse('doc:editor', args=[self.object.id, ])


class DocEditorView(LoginRequiredMixin, DocExtractMixin, DetailView):
    queryset = models.Doc.objects
    template_name = 'doc/editor.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['markdown_content'] = (self.object.get_markdown_path() / 'index.md').read_text(encoding='utf-8')
        # context['markdown_media'] = self.object.get_media_url()
        context['markdown_load_action'] = reverse('api:doc:markdown_load', args=[self.kwargs['pk'], ])
        context['markdown_save_action'] = reverse('api:doc:markdown_save', args=[self.kwargs['pk'], ])
        return context


class DocNavigatorList(LoginRequiredMixin, ListView):
    template_name = 'doc/navigator_list.html'

    def get_queryset(self):
        pool = urllib3.PoolManager()
        url = settings.SPNAVIGATOR_API.format(url='storage/document')
        res = pool.request('GET', url, headers={'Authorization': 'Token39 {}'.format(self.request.user.profile.token39)})
        data = json.loads(res.data.decode('utf-8'))
        if res.status == status.HTTP_200_OK:
            for doc in data:
                if doc['created']:
                    doc['created'] = dateparse.parse_datetime(doc['created'])
                if doc['modified']:
                    doc['modified'] = dateparse.parse_datetime(doc['modified'])
            return data
        else:
            if 'detail' in data:
                messages.error(self.request, 'Ошибка: {}'.format(data['detail']))
            else:
                messages.error(self.request, 'Неизвестная ошибка')
            return []

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['doc__category__code__list'] = sorted(list(set([(x['category']['id'], x['category']['name']) for x in self.object_list])), key=itemgetter(1))
        return context


class DocNavigatorEditorView(LoginRequiredMixin, TemplateView):
    template_name = 'doc/editor.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['markdown_load_action'] = reverse('api:doc:markdown_navigator_load', args=[self.kwargs['pk'], ])
        context['markdown_save_action'] = reverse('api:doc:markdown_navigator_save', args=[self.kwargs['pk'], ])
        return context


class DocDownloadView(LoginRequiredMixin, DetailView):
    queryset = models.Doc.objects

    def get(self, request, *args, **kwargs):
        doc = self.get_object()
        md = doc.get_markdown_filepath().read_text('utf-8')
        images = [x.groups() for x in re.finditer(r'!\[[^\]]*\]\(([^\)]+)\.(\w+)\)', md)]
        zip_stream = BytesIO()
        with ZipFile(zip_stream, 'a') as f:
            f.write(doc.get_markdown_filepath(), 'index.md')
            for name, ext in images:
                filename = '{}.{}'.format(name, ext)
                f.write(doc.get_media_path() / filename, filename)
        zip_stream.seek(0)
        response = HttpResponse(zip_stream, content_type='application/zip')
        response['Content-Disposition'] = rfc5987_content_disposition(doc.name.replace(" ", "_") + '.zip')
        return response

templates/doc/create.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Редактирование текста</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% static 'index.html' %}"><i class="fa fa-home"></i> </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'doc:list' %}">Статьи</a>
                </li>
                <li class="breadcrumb-item active">
                    Добавить
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title pb-4">
                        <h5>
                            Добавление документа
                        </h5>
                        <div class="ibox-tools">
                            <a href="{% url 'doc:create' %}" class="btn btn-primary"><i class="fa fa-plus"></i> Добавить</a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <form method="post" enctype="multipart/form-data">{% csrf_token %}
                            {% for f in form %}
                                <div class="form-group row"><label class="col-lg-2 col-form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                                    <div class="col-lg-10">
                                        {{ f }}
                                        {% if f.errors %}<label class="error" for="{{ f.id_for_label }}">{{ f.errors }}</label>{{% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="hr-line-dashed"></div>
                            <div class="form-group row">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <a class="btn btn-white btn-sm" href="{% url 'doc:list' %}">Отменить</a>
                                    <button class="btn btn-primary btn-sm" type="submit">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/doc/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Список документов</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="index.html"><i class="fa fa-home"></i> </a>
                </li>
                <li class="breadcrumb-item">
                    <strong>Список документов</strong>
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title pb-4">
                        <h5>
                            Список документов
                        </h5>
                        <div class="ibox-tools">
                            <form action="{% url 'doc:filter' %}" method="get">
                                {{ filter.form }}
                                <input class="btn btn-primary" type="submit" value="Фильтровать"/>
                            </form>
                            <a href="{% url 'doc:create' %}" class="btn btn-primary"><i class="fa fa-plus"></i> Добавить</a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <table class="table table-striped">
                            <thead>
                            <tr>
{#                              <th>#</th>#}
                                <th>Название</th>
                                <th>Проект</th>
                                <th>Статус</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for doc in object_list %}
                                <tr>
{#                                  <td>{{ doc.id }}</td>#}
                                    <td>{{ doc.name }}</td>
                                    <td>{{ doc.project }}</td>
                                    <td>{{ doc.get_status_display }}</td>
                                    <td style="white-space: nowrap">
                                        <a href="{% url 'doc:update' doc.pk %}" class="btn btn-sm btn-secondary">Изменить</a>
                                        <a href="{% url 'doc:editor' doc.pk %}" class="btn btn-sm btn-primary">Редактор</a>
                                        {% if doc.status == doc.STATUS_PREPARED %}
                                            <a href="{% url 'doc:download' doc.pk %}" class="btn btn-sm btn-success">Скачать</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/doc/navigator_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Список документов</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="index.html"><i class="fa fa-home"></i> </a>
                </li>
                <li class="breadcrumb-item">
                    <strong>Список документов</strong>
                </li>
            </ol>
        </div>
    </div>
    {% if messages %}
        <div class="col-lg-12 mt-3">
            <div class="panel panel-default ">
                <div class="panel-heading">
                    Внимание!
                </div>
                <div class="panel-body">
                    <table class="table">
                        <tbody>
                        {% for message in messages %}
                            <tr>
                                <td>
                                    <div class="{% if message.tags %}bg-{{ message.tags }}{% endif %} p-xs b-r-sm">{{ message }}</div>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    {% endif %}
    <div class="col-lg-12">
        <div class="ibox ">
            <div class="ibox-title pb-4">
                <h5>
                    Список документов
                </h5>

            </div>
            <div class="ibox-content">
                <div class="row">
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label class="col-form-label" for="doc__name">Название</label>
                            <input type="text" id="doc__name" name="doc__name" value="" placeholder="Название документа" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="form-group">
                            <label class="col-form-label" for="doc__category__code">Тип</label>
                            <select name="doc__category__code" id="doc__category__code" class="form-control">
                                <option value="0">--- все ---</option>
                                {% for code, name in doc__category__code__list %}
                                    <option value="{{ code }}">{{ name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                </div>
                <table class="table table-striped" id="doc-list">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Активно</th>
                        <th>Название</th>
                        <th>Категория</th>
                        <th>Создано</th>
                        <th>Изменено</th>
                        <th>&nbsp;</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for doc in object_list %}
                        <tr id="document-{{ doc.id }}">
                            <td>{% if doc.is_active %}<i class="fa fa-check-circle"></i>{% endif %} </td>
                            <td data-fieldname="short_name">{{ doc.short_name }}</td>
                            <td data-fieldname="category__code" data-category-id="{{ doc.category.id }}">{{ doc.category.code }}</td>
                            <td>{{ doc.modified|date:"SHORT_DATE_FORMAT" }}</td>
                            <td>{{ doc.created|date:"SHORT_DATE_FORMAT" }}</td>
                            <td><a href="{% url 'doc:navigator_editor' doc.uid %}" class="btn btn-xs btn-primary">Редактировать</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/lodash.js' %}"></script>
    <script>
        function filterTagList() {
            if ($('#doc__name').val()) {
                $('#doc-list').find('td[data-fieldname="short_name"]').parent().hide();
                $('#doc-list').find('td[data-fieldname="short_name"]:contains("' + $('#doc__name').val() + '")').parent().show();
            } else {
                $('#doc-list').find('td[data-fieldname="short_name"]').parent().show();
            }

            if ($('#doc__category__code').val() > 0) {
                $('#doc-list').find('td[data-fieldname="category__code"][data-category-id!="' + $('#doc__category__code').val() + '"]').parent().hide()
            }
        }

        $(function () {
            $('#doc__name').on('keyup', _.debounce(filterTagList, 500));
            $('#doc__category__code').on('change', _.debounce(filterTagList, 500))
        });
    </script>

{% endblock %}

templates/doc/update.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Редактирование текста</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% static 'index.html' %}"><i class="fa fa-home"></i> </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'doc:list' %}">Статьи</a>
                </li>
                <li class="breadcrumb-item active">
                    {{ object.name }}
                </li>
            </ol>
        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        {% if unknown_colors %}
            <div class="row">
                <div class="col-lg-12">
                    <div class="ibox ">
                        <div class="ibox-title pb-4">
                            <h5>
                                Неизвестные цвета
                            </h5>
                        </div>
                        <div class="ibox-content">
                            {% for color, x in unknown_colors.items %}
                                <div class="row">
                                    <div class="col-4">
                                        {{ color }}
                                    </div>
                                    <div class="col-8">
                                        {% for y in x %}
                                            <div style="{{ y.style }}">
                                                {{ y.text }}
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                <hr/>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title pb-4">
                        <h5>
                            Добавление документа
                        </h5>
                        <div class="ibox-tools">
                            <a href="{% url 'doc:create' %}" class="btn btn-primary"><i class="fa fa-plus"></i> Добавить</a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <form method="post" enctype="multipart/form-data">{% csrf_token %}
                            {% for f in form %}
                                <div class="form-group row"><label class="col-lg-2 col-form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                                    <div class="col-lg-10">
                                        {{ f }}
                                        {% if f.errors %}<label class="error" for="{{ f.id_for_label }}">{{ f.errors }}</label>{{% endif %}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="hr-line-dashed"></div>
                            <div class="form-group row">
                                <div class="col-sm-4 col-sm-offset-2">
                                    <a class="btn btn-white btn-sm" href="{% url 'doc:list' %}">Отменить</a>
                                    <button class="btn btn-primary btn-sm" type="submit">Сохранить</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}